
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/facebookgo/stack"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "github.com/mediocregopher/radix.v3"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/securecookie"


[[constraint]]
  name = "github.com/spf13/viper"
  revision = "25b30aa063fc18e48662b86996252eabdcf2f0c7"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/codahale/http-handlers"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"
